### ISSUE TITLE
having problems with the globaldb example

### ISSUE THREAD

**Issue by stiangrindvoll** [ipfs/go-ds-crdt#17]
Setup:
Two nodes on local network, no firewalls. 
Node **A** runs ipfs node with ipfs pubsub enabled (not sure if needed) **ipfs v0.4.22**
Node **A** Also run a globaldb example connecting to the ipfs bootstrap node on its own host.
Node **B** also runs globaldb example

Node B:
```
> put crdt example
11:49:45.071 DEBUG   globaldb: processing generated block QmSEQ6ZnEs5VpkWEszhDzyHdVebdrS6kijyDJA7M6sy78K crdt.go:719
Added: [/crdt] -> example
11:49:45.076 DEBUG   globaldb: merged delta from QmSEQ6ZnEs5VpkWEszhDzyHdVebdrS6kijyDJA7M6sy78K (priority: 4) crdt.go:483
11:49:45.076  INFO   globaldb: replacing DAG head: QmRrU4aNRRD1zDAnKXvbVcphhu6tFuHN4F2TZdc9noz6MP -> QmSEQ6ZnEs5VpkWEszhDzyHdVebdrS6kijyDJA7M6sy78K (new height: 4) heads.go:82
11:49:45.080 DEBUG   globaldb: broadcasting QmSEQ6ZnEs5VpkWEszhDzyHdVebdrS6kijyDJA7M6sy78K crdt.go:741
> 11:49:45.083 DEBUG   globaldb: QmSEQ6ZnEs5VpkWEszhDzyHdVebdrS6kijyDJA7M6sy78K is known. Skip walking tree crdt.go:368

> get crdt
[/crdt] -> example

```

Can see that the DAG is available on ipfs bootstrap node (A).
```
$ ipfs dag get QmRrU4aNRRD1zDAnKXvbVcphhu6tFuHN4F2TZdc9noz6MP
{"data":"ChAKBS9jcmR0GgdleGFtcGxlGAM=","links":[{"Cid":{"/":"QmanLnLu3BUFpQFjmZNw3Rn57gL3TnZwuQFyqpcL8xXLZ5"},"Name":"","Size":0}]}
```

But it is not syncing up with node A's globaldb example:
```
get crdt
error: datastore: key not found
> 
```

Both node A and B are connected to same peers
```
debug peers
/ip4/10.82.8.154/tcp/4001/ipfs/QmQGCvFWHguGFVvJswtRSyaHhmtgBcarjR877ap34yHDHQ

```

As a side note, i upgraded the globaldb example's to latest go modules as well, to test both in this current master and with latest. No change in behavior.

**I'm wondering what i'm missing, or if there is anything that needs to be set up in addition.**

**Comment by hsanjuan** [comment]
Is NodeA-globaldb connected to NodeB-globaldb though? If not try replacing the bootstrap address with that of the other globaldb peer. Alternatively, if you want to bootstrap to your ipfs peer from both global db peers, you could subscribe that peer to the pubsub topic (`ipfs pubsub sub globaldb-example`) and that might start getting the messages across from A to B (if both are connected to that ipfs node).

I had bigger plans for this example (to keep a mini-network of participants running etc) but never got around. Technically, this is fully independent from any ipfs daemon other than it used the public network to bootstrap which would allow it to use the public DHT to find providers for the merkle-crdt heads. However that seems pretty useless as the example stands right now because the initial discovery of at least one other global-db peer is not there therefore pubsub messages are getting there and nothing works.

**Comment by stiangrindvoll** [comment]
Thank you

It seems that there are no new peer discoveries when using my **A** ipfs node as bootstrap, if i add another one on the internet (same setup as my local). A-globaldb and B-globaldb will eventually discovery each other. It can be quick, but most of the time it can take some time, This is essentially a discovery problem it seem. 

I had the assumption it would be enough to be connected to the same bootstrap node, but for that i might have to activate relay?

Obviously manually adding A-globaldb and B-globaldb as bootstrap nodes is not ideal, and would need the nodes to discover each other quicker, specially since they are actually connecting to the same bootstrap nodes. 
Can one use the ipfsDHT features to speed up the process? Or is this already happening at some other layer?
* https://godoc.org/github.com/libp2p/go-libp2p-kad-dht#IpfsDHT.FindProviders
* https://godoc.org/github.com/libp2p/go-libp2p-kad-dht#IpfsDHT.Provide

**Comment by stiangrindvoll** [comment]
Hmm yes, i managed to speed it up (in my own implementation for a game i'm trying to make). this will bootstrap first once as in the globaldb example. then provide your appearance to the dht topic and search for other providers. Then bootstrap again with the found peers appended.

This gives a pretty much instant connection so far, but feels a little blunt. Any other suggestion?

**Comment by hsanjuan** [comment]
> if i add another one on the internet (same setup as my local). A-globaldb and B-globaldb will eventually discovery each other.

Weird, but again, the fact they discover and connect to each other is pretty random and depends on dht-walk and how dht-buckets are filled.

For bootstrap discovery and connectivity in p2p you want:
- mdns
- Relay
- AutoNATSvc and Autonat enabled
- The provide a topic on the dht and look for other providers of it is a good idea. Instead of Bootstrap() just do a host.Connect() to those peers (although doing ipfs.Bootstrap() again might also work all the same - as long as the dht.Bootstrap() call inside does not cause problems when called multiple times).

Usually this is much better on a private network where all the peers are subscribed to the pubsub topic because then the messages will travel around even if they are not all interconnected. In the public network, the density of topic-subscribed peers is not going to be enough.

**Comment by hsanjuan** [comment]
This is a bit old so I'll close it. Re-open as needed.
